trigger:
  - main

pool: Roboshop-workstation

variables:
  COMPONENT: shipping

resources:
  repositories:
    - repository: templates
      type: github
      name: dailypractice-all/roboshop-azure-devops-templates
      endpoint: dailypractice-all

stages:
- template: maven.yml@templates